# Setup
baseurl:          "/flash_cc2531"
auxtoro: Jean Michault
# malkomentigu la sekvan linion por forigi la menuon "ĉiuj afiŝoj"
ne_afisxoj: "true"
# malkomentigu la sekvan linion por forigi la menuon "serĉu per google"
#ne_googlesearch: "true"


# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

exclude: [ _locale , _scripts , "*.backup", "*.bak" ]

plugins:
  - jekyll-relative-links
  - jekyll-sitemap

relative_links:
  enabled:     true
  collections: true
